WITH FOR_INV_AMT_AGGREGATION AS (
SELECT DISTINCT
INV.LOADNUM 
,INV.BRANCHCODE
,INV.CUSTOMERCODE
,CAST(INV.RELEASEDDATE AS DATE) AS "RELEASEDDATE"
,SUM(INV.SOURCEADJUSTEDINVOICEAMOUNT) AS "ADJUSTEDINVOICEAMOUNT"
,SUM(INV.SOURCERECEIVEDAMOUNT) AS "RECEIVEDAMOUNT"
,SUM(INV.SOURCEINVOICEBALANCE) AS "INVOICEBALANCE"
,SUM(INV.SOURCEINVOICEAMOUNT) AS "INVOICEAMOUNT"
,INV.REFERENCENUM 
,MAX(INV.LASTRECEIPTDATE) AS "LASTRECEIPTDATE_1"
,INV.INVOICEDOCID
,INV.PRINTDATE 
,ID.INVOICENUM
FROM
 CDC_FINANCIALS.BROKER.DBO_INVOICE INV
 LEFT JOIN CDC_FINANCIALS.BROKER.DBO_INVOICEDOC ID
	ON INV.INVOICEDOCID = ID.INVOICEDOCID
    AND ID.HVR_ISDELETE = 0
WHERE
    INV.HVR_ISDELETE = 0 AND INV.RELEASEDDATE IS NOT NULL AND INV.CUSTOMERCODE = 'C8147803' AND INV.PRINTDATE IS NOT NULL AND INV.STATUS = 'O' --AND INV.LOADNUM = 425714220
GROUP BY ALL
)

,bucketed AS (
    SELECT
        LOAD_NUMBER AS nav_load_number,
        BILLING_PARTY_CODE AS customer_code,
        CHR_INVOICE_NUMBER AS invoice_number,
        INVOICE_DATE::DATE AS invoice_date,
        COALESCE(NULLIF(TRIM(CHARGE_DESCRIPTION),''),'UNMAPPED_CHARGE_DESCRIPTION') AS charge_code_description,
        ROUND(CHARGE_TOTAL_AMOUNT,2)::NUMBER(18,2) AS charge_amount,
        CASE
            WHEN CHARGE_TYPE IN ('Customs','Duty+Tax')
              OR RATE_CODE IN ('CCE','CEX','CIF','CUS','DUF','DUT','HMF','INF','MPF')
              OR REGEXP_LIKE(charge_code_description,'CUSTOMS|DUTY|TAX|BROKERAGE|CLEARANCE|HMF|MPF','i')
                THEN 'DESTINATION_CUSTOMS'

            WHEN CHARGE_TYPE='Freight'
              OR RATE_CODE IN ('400','405','BSC')
              OR REGEXP_LIKE(charge_code_description,'FREIGHT|LINEHAUL|OCEAN|AIR FREIGHT','i')
                THEN 'FREIGHT'

            WHEN REGEXP_LIKE(charge_code_description,'ORIGIN|PICKUP|EXPORT|BOOKING|DOC|HANDLING ORIGIN','i')
                THEN 'ORIGIN'

            WHEN REGEXP_LIKE(charge_code_description,'DESTINATION|DELIVERY|ARRIVAL|DECONSOL|DEVAN|HANDLING DEST','i')
                THEN 'DESTINATION'

            ELSE 'ACCESSORIAL_OTHER'
        END AS charge_bucket
    FROM GF_COMMERCIAL_DOMAIN.BROKER.GF_BILLING
    WHERE BILLING_PARTY_CODE='C8147803'
      AND INVOICE_DATE >= DATE '2025-01-01'
      AND INVOICE_EXEMPT='FALSE'
      AND PLANNED_INVOICE='Invoiced'
)

,Bucket_total AS (
SELECT
    nav_load_number,
    customer_code,
    invoice_date,
    invoice_number,
    ROUND(SUM(charge_amount),2) AS load_invoice_total,
    ROUND(SUM(IFF(charge_bucket='ORIGIN',charge_amount,0)),2) AS origin_total,
    ROUND(SUM(IFF(charge_bucket='FREIGHT',charge_amount,0)),2) AS freight_total,
    ROUND(SUM(IFF(charge_bucket='DESTINATION',charge_amount,0)),2) AS destination_total,
    ROUND(SUM(IFF(charge_bucket='DESTINATION_CUSTOMS',charge_amount,0)),2) AS destination_customs_total,
    ROUND(SUM(IFF(charge_bucket='ACCESSORIAL_OTHER',charge_amount,0)),2) AS accessorial_other_total
FROM bucketed
GROUP BY ALL
)

,each_charge_code AS (
SELECT DISTINCT
        B.LOAD_NUMBER AS nav_load_number,
        B.CHR_INVOICE_NUMBER AS invoice_number,
        CAST(B.INVOICE_DATE AS DATE) AS invoice_date,
        B.BILLING_PARTY_CODE AS customer_code,
        SUM(CASE WHEN RATE_CODE = '405' THEN CHARGE_TOTAL_AMOUNT END) AS "405", SUM(CASE WHEN RATE_CODE = '400' THEN CHARGE_TOTAL_AMOUNT END) AS "400",                SUM(CASE WHEN RATE_CODE = '800' THEN CHARGE_TOTAL_AMOUNT END) AS "800", SUM(CASE WHEN RATE_CODE = 'WHF' THEN CHARGE_TOTAL_AMOUNT END) AS "WHF",                SUM(CASE WHEN RATE_CODE = 'FAF' THEN CHARGE_TOTAL_AMOUNT END) AS "FAF", SUM(CASE WHEN RATE_CODE = 'CTG' THEN CHARGE_TOTAL_AMOUNT END) AS "CTG",                SUM(CASE WHEN RATE_CODE = '075' THEN CHARGE_TOTAL_AMOUNT END) AS "075"
    FROM GF_COMMERCIAL_DOMAIN.BROKER.GF_BILLING B
    WHERE B.BILLING_PARTY_CODE = 'C8147803'
      AND B.INVOICE_DATE >= DATE '2025-01-01'
      AND B.INVOICE_EXEMPT = 'FALSE'
      AND B.PLANNED_INVOICE = 'Invoiced'
    GROUP BY ALL
    ORDER BY B.CHR_INVOICE_NUMBER 
)

SELECT DISTINCT
 --INV.BRANCHCODE AS "Branch"
BUT.INVOICE_NUMBER AS "Invoice#"
,INV.LOADNUM AS "Load Number"
,CASE WHEN LSI.MODE = 'A' AND LSI.DESTINATIONCOUNTRY <> 'IN' THEN 'Air Consolidation Services Export' 
     WHEN LSI.MODE = 'A' AND LSI.DESTINATIONCOUNTRY = 'IN' THEN 'Air Consolidation Services Import' 
     WHEN LSI.MODE = 'S' AND LSI.DESTINATIONCOUNTRY <> 'IN' THEN 'Ocean NVOCC Services Export' 
     WHEN LSI.MODE = 'S' AND LSI.DESTINATIONCOUNTRY = 'IN' THEN 'Ocean NVOCC Services Import ' 
     ELSE GFS.MODE END AS "Source Mode Description"
,GFS.MBL_NUMBER AS "MBL"
,GFS.HBL_NUMBER AS "HBL"
,GFS.CONTAINER_NUMBERS AS "# Containers"
,GFS.ORIGIN_PORT_AIRPORT_DEPARTED AS "Origin Port ATD"
,GFS.DESTINATION_PORT_AIRPORT_ARRIVED AS "Destination Port ATA"
,INV.PRINTDATE AS "Invoice Print Date"
,GFS.ORIGIN_PORT_AIRPORT_NAME AS "Origin Port"
,GFS.PICKUP_FROM_NAME AS "Origin Door Stop"
,GFS.DESTINATION_PORT_AIRPORT_NAME AS "Destination Port"
,GFS.DELIVER_TO_NAME AS "Destination Door Stop"
,GFS.SHIPPER_NAME AS "Supplier"
,INV.INVOICEAMOUNT AS "Invoice Orig. Amount/ Total"
,CASE WHEN INV.ADJUSTEDINVOICEAMOUNT IS NULL THEN INV.INVOICEAMOUNT
      WHEN INV.ADJUSTEDINVOICEAMOUNT < INV.INVOICEBALANCE THEN INV.INVOICEBALANCE
      ELSE INV.ADJUSTEDINVOICEAMOUNT END AS "Invoice Adj. Amount/Total"
,BUT.freight_total AS "Intl Freight Total"
,BUT.origin_total AS "Origin Services Total"
,BUT.accessorial_other_total AS "Regulatory Filings Total"
,BUT.destination_total AS "Destination Services Total"
,BUT.destination_customs_total AS "Dest Customs Total"
,CCR.* EXCLUDE (nav_load_number,invoice_number, invoice_date, customer_code)
      
FROM  GF_COMMERCIAL_DOMAIN.BROKER.GF_SHIPMENTS GFS
LEFT JOIN CDC_EXPRESS.BROKER.DBO_LOADSUMMARYINTL LSI
    ON GFS.SHIPMENT_NUMBER = LSI.LOADNUM
LEFT JOIN FOR_INV_AMT_AGGREGATION INV
    ON GFS.SHIPMENT_NUMBER = INV.LOADNUM
RIGHT JOIN Bucket_total BUT
    ON GFS.SHIPMENT_NUMBER = BUT.nav_load_number
    AND INV.CUSTOMERCODE = BUT.customer_code
    AND INV.INVOICENUM= BUT.invoice_number
LEFT JOIN each_charge_code CCR
    ON BUT.nav_load_number = CCR.nav_load_number
    AND BUT.customer_code = CCR.customer_code
    AND BUT.invoice_number = CCR.invoice_number


WHERE INV.CUSTOMERCODE = 'C8147803'
AND INV.INVOICEBALANCE <> 0 
AND BUT.INVOICE_DATE >= DATE '2025-01-01'
--AND INV.LOADNUM = 544642775
;

